### ISSUE TITLE
Add option display frequency as Y-axis in graph 

### ISSUE THREAD

**Issue by gregory-nisbet** [rhiever/name-age-calculator#1]
I think it'd be useful for the graph visualization to allow people to visualize the frequency of the name at various points in time, in addition to absolute number of births/namings

**Comment by rhiever** [comment]
Hi Gregory. Do you mean something like [this](http://rhiever.github.io/baby-name-explorer/)?

**Comment by gregory-nisbet** [comment]
Yes. I didn't realize you had a separate project already for that.

**Comment by rhiever** [comment]
:+1:
